/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ontap;

import java.awt.event.WindowEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class HCNJFrame extends javax.swing.JFrame {

    private JFrame frame;
    private  int id = 0;
    /**
     * Creates new form HCNJFrame
     */
    public HCNJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrTinhTrang = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        textMaMau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textChieuDai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textChieuRong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textSoLuong = new javax.swing.JTextField();
        btnTinhTrangKhongCon = new javax.swing.JRadioButton();
        btnTinhTrangCon = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnThemHinhChuNhat = new javax.swing.JButton();
        btnLuuDuLieu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("mã màu");

        textMaMau.setName("textmausac"); // NOI18N
        textMaMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaMauActionPerformed(evt);
            }
        });

        jLabel2.setText("chiều dài");

        textChieuDai.setName("textchieudai"); // NOI18N
        textChieuDai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textChieuDaiActionPerformed(evt);
            }
        });

        jLabel3.setText("chiều rộng");

        textChieuRong.setName("textchieurong"); // NOI18N
        textChieuRong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textChieuRongActionPerformed(evt);
            }
        });

        jLabel4.setText("số lượng");

        textSoLuong.setName("textchieurong"); // NOI18N
        textSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSoLuongActionPerformed(evt);
            }
        });

        btngrTinhTrang.add(btnTinhTrangKhongCon);
        btnTinhTrangKhongCon.setText("không còn");
        btnTinhTrangKhongCon.setName("tinhtrang"); // NOI18N
        btnTinhTrangKhongCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTrangKhongConActionPerformed(evt);
            }
        });

        btngrTinhTrang.add(btnTinhTrangCon);
        btnTinhTrangCon.setText("còn");
        btnTinhTrangCon.setName("tinhtrang"); // NOI18N
        btnTinhTrangCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTrangConActionPerformed(evt);
            }
        });

        jLabel5.setText("tình trạng ");

        btnThemHinhChuNhat.setText("Thêm Hình Chữ Nhật");
        btnThemHinhChuNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHinhChuNhatActionPerformed(evt);
            }
        });

        btnLuuDuLieu.setText("Lưu Dữ Liệu");
        btnLuuDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuDuLieuActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("Hình Chữ Nhât");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textChieuRong, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textChieuDai, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(74, 74, 74)
                                .addComponent(textMaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTinhTrangCon)
                                        .addGap(76, 76, 76)
                                        .addComponent(btnTinhTrangKhongCon))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThemHinhChuNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLuuDuLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel6)))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textMaMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textChieuDai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textChieuRong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTinhTrangCon)
                    .addComponent(btnTinhTrangKhongCon)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addComponent(btnThemHinhChuNhat)
                .addGap(40, 40, 40)
                .addComponent(btnLuuDuLieu)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMaMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMaMauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMaMauActionPerformed

    private void textChieuDaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textChieuDaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textChieuDaiActionPerformed

    private void textChieuRongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textChieuRongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textChieuRongActionPerformed

    private void textSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSoLuongActionPerformed

    private void btnTinhTrangKhongConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTrangKhongConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTinhTrangKhongConActionPerformed

    private void btnTinhTrangConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTrangConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTinhTrangConActionPerformed

    private void btnThemHinhChuNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHinhChuNhatActionPerformed
        // TODO add your handling code here:
        String maumau = textMaMau.getText();
        String chieudai = textChieuDai.getText();
        String chieurong = textChieuRong.getText();
        String soluong = textSoLuong.getText();
        boolean check = false;
        if (btnTinhTrangCon.isSelected()) {
            check = true;
        }
        if (btnTinhTrangKhongCon.isSelected()) {
            check = false;
        }
        String tinhtrang = null;
        if (check == true) {
            tinhtrang = "con";
        } else {
            tinhtrang = "khong con";
        }

        JOptionPane.showMessageDialog(btnThemHinhChuNhat, maumau + chieudai + chieurong + soluong + tinhtrang, "Thong tin hinh chu nhat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnThemHinhChuNhatActionPerformed

    private void btnLuuDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuDuLieuActionPerformed
        String maumau = textMaMau.getText();
        float chieudai = Float.parseFloat(textChieuDai.getText());
        float chieurong = Float.parseFloat(textChieuRong.getText());
        int soluong = Integer.parseInt(textSoLuong.getText());
        boolean check = false;
        if (btnTinhTrangCon.isSelected()) {
            check = true;
        }
        if (btnTinhTrangKhongCon.isSelected()) {
            check = false;
        }
        String tinhtrang = null;
        if (check == true) {
            tinhtrang = "con";
        } else {
            tinhtrang = "khong con";
        }
        String file = "hcn.data";
        KhoHang khoHang = new KhoHang(soluong, tinhtrang);
        HinhChuNhat hinhChuNhat = new HinhChuNhat(Integer.toString(id=id + 1), maumau, chieudai, chieurong, khoHang);
        int luaChon = JOptionPane.showConfirmDialog(frame, "Ban thuc su co muon luu khong?", "luu", JOptionPane.YES_NO_OPTION);
        if (luaChon == JOptionPane.YES_OPTION) {
            FileWriter fileWriter;
            try {
                fileWriter = new FileWriter(file, true);
                PrintWriter printWriter = new PrintWriter(fileWriter);
                printWriter.println(hinhChuNhat.getMahinh());
                printWriter.println(hinhChuNhat.getMausac());
                printWriter.println(hinhChuNhat.getChieudai());
                printWriter.println(hinhChuNhat.getChieurang());
                printWriter.println(hinhChuNhat.getKhoHang().getSoluong());
                printWriter.println(hinhChuNhat.getKhoHang().getConhang());
                printWriter.close();
                fileWriter.close();
            } catch (IOException ex) {
                Logger.getLogger(HCNJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }

    }//GEN-LAST:event_btnLuuDuLieuActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int luaChon = JOptionPane.showConfirmDialog(frame, "Ban thuc su co muon thoat khong?", "Thoat", JOptionPane.YES_NO_OPTION);
        if (luaChon == JOptionPane.YES_OPTION) {
            System.exit(1);
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HCNJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HCNJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HCNJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HCNJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HCNJFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuDuLieu;
    private javax.swing.JButton btnThemHinhChuNhat;
    private javax.swing.JRadioButton btnTinhTrangCon;
    private javax.swing.JRadioButton btnTinhTrangKhongCon;
    private javax.swing.ButtonGroup btngrTinhTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField textChieuDai;
    private javax.swing.JTextField textChieuRong;
    private javax.swing.JTextField textMaMau;
    private javax.swing.JTextField textSoLuong;
    // End of variables declaration//GEN-END:variables
}
